---
name: docs-preview-cleanup

on:
  pull_request_target:
    types:
      - closed

permissions: {}

jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@e9cc8a02418ec86036ebe5a220f9c3a4a80aaa1d # v1
    permissions:
      contents: none
      id-token: write
      deployments: write
